name: Job set up
description: Sets up the Java and Gradle

runs:
  using: "composite"
  steps:

  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: '17'
      distribution: 'temurin'

  - name: Grant execute permission for gradlew
    shell: bash
    run: chmod +x gradlew

  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v4
    with:
      gradle-version: 'wrapper'
      validate-wrappers: true
      gradle-home-cache-cleanup: true

  - name: Cache Gradle dependencies
    uses: actions/cache@v4
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      restore-keys: |
        ${{ runner.os }}-gradle-